### ISSUE TITLE
Configure.py option 2 (test configuration) is not functioning

### ISSUE THREAD

**Issue by Turnyanskiy** [Luois45/DiscordShopBot#21]
**Replicate By:**
- Filling in option 1 with valid arguments
- Running option 2 after save and re-running the program

**Reason:**
- Currently program opens "defualt-config.json" at the beginning and withdraws all information from it. This is required as option 1 requires the user to fill in the installation details. 
- When running option 2, the program uses "defualt-config.json" values rather than the vlaues in "config.json", which was created whilst running option 1. This of course results in an error as the programme is unable to test the connection with false values.

**Comment by Turnyanskiy** [comment]
-In addition option 1 saves port number as an string. This means option 2, when attempting to connect to the mysql server, fills the port parameter with a string rather than tan integer, as expected.

**Comment by Luois45** [comment]
The port parameter is meant to be filled with a string.

**Comment by Turnyanskiy** [comment]
Not according to my test and official documentation: [https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html]()

Also the main issue, which is option 2 looking for values from "defualt-config.json", still remains...

@Luois45 please could you reopen the issue (even if port parameter is expecting a string and I am wrong, as the main issue is still relevant), thank you.

**Comment by Luois45** [comment]
It doesn't make a difference if you input a string containing an int or directly an int for the port.
That's why it is functioning.
But it would still be an improvement if the port in the config would be handled as an int.
