### ISSUE TITLE
 No reaction to commands

### ISSUE THREAD

**Issue by Diggeris** [Luois45/DiscordShopBot#28]
No reaction to commands.

Operating System: Ubuntu 20.04.5 LTS
Kernel: Linux 5.4.0-124-generic
Architecture: x86-64
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
Python 3.8.10

MySQL is OK, Bot created a tables in DB
Discord bot is OK. I was using python configure.py to configure my bot, after configure I launched the bot and it doesn't react to any commands

**Comment by Luois45** [comment]
Did you assign the correct role (Seller) to yourself?

**Comment by gOOvER** [comment]
can't confirm; bot commands works fine

**Comment by Diggeris** [comment]
Bot didin't worked on discord.py==1.5.1 version. It's very old issue. Case closed.
