### ISSUE TITLE
Orders are not created in ORDERS category

### ISSUE THREAD

**Issue by gOOvER** [Luois45/DiscordShopBot#40]
I have running the bot and assigned me to Seller Role. i used =setup and the category ORDERS was created.

When i create an order, the order is not in ORDERS. 

![Discord_F7wTsfQK8x](https://user-images.githubusercontent.com/116325/212470854-b53db257-1ca8-409e-977a-e7598ed79c3c.png)

**Comment by Luois45** [comment]
The category create command is not for something like an order's category. It's just for creating categories.

**Comment by Luois45** [comment]
Inactive for a month and archived due to this.
Will be reopened on further activity.
