### ISSUE TITLE
invit bloked

### ISSUE THREAD

**Issue by mimio10** [Luois45/DiscordShopBot#41]
![image](https://user-images.githubusercontent.com/54474082/212790451-22e190db-4c12-41b1-b82b-98e88bad6974.png)

**Comment by Luois45** [comment]
I'm aware of the problem existing at the moment and can't do anything about it.
For clearificaiton this is what I get from discord side:
![image](https://user-images.githubusercontent.com/58306774/219175169-c2b7d042-840a-41a8-8484-d95fe0a27f50.png)

**Comment by Luois45** [comment]
@mimio10 Got the problem solved. It was a problem in the configuration because it was completely unclear to me what two of the privileges enable/disable buttons did in the background
